package com.ann

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
    def filters = {
        all(uri: "/**") {
            before = {
                // Ignore direct views (e.g. the default main index page).
                if (!controllerName) return true
				if (
					(controllerName=="public") ||
					(controllerName=="xmlData")
					) return true      // Public Controller的網頁不經由權限控制
                // 其他的都需要經由log in 確認. 
                accessControl()
            }
        }
    }
}
